name: Ticket Automation Bot
on:
  issues:
    types: [opened, closed, reopened, labeled, unlabeled, edited]
  discussion:
    types: [created]
jobs:
  manage-ticket-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      discussions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install @octokit/rest
      - name: Manage Ticket Folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          EVENT_TYPE: ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
          ISSUE_NUMBER: ${{ github.event.issue.number || github.event.discussion.number }}
        run: node .github/scripts/ticket-automation.js
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tickets/ resolved/
          if [ "${{ github.event_name }}" == "issues" ]; then
            if [ "${{ github.event.action }}" == "closed" ]; then
              git commit -m "Move ticket folder to resolved for closed issue #${{ github.event.issue.number }}"
            elif [ "${{ github.event.action }}" == "reopened" ]; then
              git commit -m "Move ticket folder back to tickets for reopened issue #${{ github.event.issue.number }}"
            elif [ "${{ github.event.action }}" == "labeled" ] || [ "${{ github.event.action }}" == "unlabeled" ] || [ "${{ github.event.action }}" == "edited" ]; then
              git commit -m "Update evaluation.md for issue #${{ github.event.issue.number }}"
            else
              git commit -m "Create ticket folder and evaluation.md for issue #${{ github.event.issue.number }}"
            fi
          elif [ "${{ github.event_name }}" == "discussion" ]; then
            git commit -m "Create ticket folder and evaluation.md for discussion #${{ github.event.discussion.number }}"
          fi
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Notify Team
        if: github.event.action == 'opened' || github.event.action == 'created' || github.event.action == 'labeled' || github.event.action == 'unlabeled'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          EVENT_TYPE: ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
          ISSUE_NUMBER: ${{ github.event.issue.number || github.event.discussion.number }}
        run: node .github/scripts/notify-team.js
        continue-on-error: true
